- id: optional-dependencies-all
  name: Update `optional.dependencies.all` in pyproject.toml
  entry: optional-dependencies-all
  language: python
  language_version: python3
  files: '(^|/)pyproject\.toml$'
  types: [file, text, toml]
